// Auto-generated by tauri-specta – wird in Phase 2 überschrieben
import { invoke } from "@tauri-apps/api/core";

export async function getWatchlist() {
  return invoke<Array<{ coin_id: string; symbol: string; name: string; added_at: string }>>("get_watchlist");
}

export async function addToWatchlist(coinId: string, symbol: string, name: string) {
  return invoke<void>("add_to_watchlist", { coinId, symbol, name });
}

export async function removeFromWatchlist(coinId: string) {
  return invoke<void>("remove_from_watchlist", { coinId });
}

export async function fetchPrices(ids: string[]) {
  return invoke<Record<string, { price: number; change24h: number; volume: number }>>("fetch_prices", { ids });
}

export async function fetchChart(coinId: string, days: number) {
  return invoke<Array<[number, number]>>("fetch_chart", { coinId, days });
}

export async function fetchNews(symbols: string[]) {
  return invoke<Array<{ title: string; url: string; source: string; sentiment: string | null }>>("fetch_news", { symbols });
}

export async function aiAnalyzeCoin(coinId: string) {
  return invoke<string>("ai_analyze_coin", { coinId });
}

export async function saveApiKey(provider: string, key: string) {
  return invoke<void>("save_api_key", { provider, key });
}

export async function getAlertRules() {
  return invoke<Array<{ id: number; coin_id: string; metric: string; operator: string; value: number; enabled: boolean }>>("get_alert_rules");
}

export async function saveAlertRule(coinId: string, metric: string, operator: string, value: number) {
  return invoke<number>("save_alert_rule", { coinId, metric, operator, value });
}

export async function deleteAlertRule(id: number) {
  return invoke<void>("delete_alert_rule", { id });
}
